---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keda-operator
  namespace: keda
  annotations:
    olm.operatorGroup: keda-operatorgroup
spec:
  channel: "alpha"
  installPlanApproval: "Automatic"
  source: "community-operators" 
  sourceNamespace: "openshift-marketplace"
  name: "keda"

