apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: argocd-controller-server
  kind: argocd-configuration
  master: argocd-application

resources:
  - argocd-controller-server-hpa.yaml
