apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: openshift-nmstate-instance
  kind: nmstate
  master: argocd-application

resources:
  - project.yaml
  - operator.yaml
