---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-logging-operator
  namespace: argocd
spec:
  project: cluster-logging-operator
  source:
    repoURL: https://github.com/mcaimi/ocp4-argocd.git
    targetRevision: HEAD
    path: logging/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

