apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: openshift-logging
  kind: operator
  master: argocd-application

resources:
  - namespaces.yaml
  - operatorgroup.yaml
  - subscription.yaml
