---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-manager
  namespace: argocd
spec:
  project: advanced-cluster-manager
  source:
    repoURL: https://github.com/mcaimi/ocp4-argocd.git
    targetRevision: HEAD
    path: acm/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

