---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-controller
  namespace: argocd
spec:
  applicationInstanceLabelKey: redhat.com/argocd-controller
  usersAnonymousEnabled: false
  ha:
    enabled: true
  dex:
    image: quay.io/dexidp/dex
    version: latest
    openShiftOAuth: true
  grafana:
    enabled: true
    route:
      enabled: true
  prometheus:
    enabled: true
    route:
      enabled: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, argocd-users, role:readonly
      g, argocd-admins, role:admin
    scopes: '[groups]'
  server:
    enabled: true
    route:
      enabled: true
    autoscale:
      enabled: true
      hpa:
        maxReplicas: 3
        minReplicas: 2
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: argocd-controller-server
        targetCPUUtilizationPercentage: 50
