apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: amq-broker-operator
  kind: operator
  master: argocd-application

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - messaging-platform-instance.yaml
  - messaging-addresses.yaml
