---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker-subscription
  namespace: amq-broker-operator
  annotations:
    olm.operatorGroup: amq-broker-operatorgroup
spec:
  channel: "7.x"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "amq-broker"
