apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: "instance"
spec:
  logStore:
    retentionPolicy:
      application:
        maxAge: 1d
      infra:
        maxAge: 7d
      audit:
        maxAge: 7d
