apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: openshift-logging
  kind: cluster-logging
  master: argocd-application

namespace: openshift-logging

patches:
  - es-storage.yaml
  - es-limits.yaml
  - es-retention.yaml

resources:
  - cluster-logging.yaml
