---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-k
  namespace: argocd
spec:
  project: camel-k
  source:
    repoURL: https://github.com/mcaimi/ocp4-argocd.git
    targetRevision: HEAD
    path: camelk/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

