apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: oc
  kind: openshift-configuration
  master: argocd-application

resources:
  - project.yaml
  - authconfig.yaml
  - argocd-config.yaml
