apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: codeready-workspaces-cluster
  kind: checluster
  master: argocd-application

resources:
  - project.yaml
  - operator.yaml
