apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: openshift-monitoring
  kind: prometheus-monitoring
  master: argocd-application

resources:
  - cluster-monitoring-cm.yaml
  - user-monitoring-cm.yaml
