apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: cluster-logging
  kind: logging-instance
  master: argocd-application

resources:
  - project.yaml
  - operator.yaml
