apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-namespace.yaml
  - argocd-admins-group.yaml
  - argocd-cluster-rolebinding.yaml
  - anyuid-scc.yaml
