apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: multi-cluster-hub
  kind: multiclusterhub
  master: argocd-application

resources:
  - project.yaml
  - clusterhub.yaml
