---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams-subscription
  namespace: argo-amq-streams-operator
  annotations:
    olm.operatorGroup: amq-streams-operatorgroup
spec:
  channel: "stable"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "amq-streams"
